<i class="footer-img fab fa-twitter"></i>                      <!-- Using font awesome icons -->
<i class="footer-img fab fa-facebook-f"></i>                   <!-- Using font awesome icons -->
<i class="footer-img fab fa-instagram"></i>                    <!-- Using font awesome icons -->
<a href="mailto:103169535@student.swin.edu.au?subject=feedback"> <i class="footer-img fas fa-envelope"></i> </a>   <!-- Using font awesome icons -->
<p class="parahighlight">©Swinburne University (Adnan Zafar)</p>
