<nav class="navbar navbar-expand-lg navbar-dark">
  <a class="navbar-brand" href=""> <i class="fas fa-location-arrow"></i>cruisEASE</a>     <!--Using fontawesome icons-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">   <!--to get hamburger menu and button class-->
    <span class="navbar-toggler-icon"></span>  <!--Getting hamburger menu using Bootstrap-->
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent"> <!--Collapsing the navbar in smaller screen-->
    <ul class="navbar-nav ml-auto">   <!--Navbar giving margin left auto-->
      <li class="nav-item">
        <a class="nav-link" href="index.php">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="product.php">Service Description</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="enquire.php">Enquiry</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="payment.php">Payment</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="about.php">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="manager.php">Manager</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="enhancements.php">Enhancements</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="enhancements2.php">JS Enhancements</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="enhancements3.php">PHP Enhancements</a>
      </li>
    </ul>
  </div>
</nav>
